### ISSUE TITLE
pannah doesn't respond to polyphonic CV

### ISSUE THREAD

**Issue by glocke01** [MockbaTheBorg/MockbaModular#11]
Sorry to be a bother!

I really want a polyphonic panner and don't like the way BogAudio's knobs switch to being CV attenuators. Pannah is the thing I need more than ready access to food. Please save me.

**Comment by MockbaTheBorg** [comment]
I will test it right now ... so the expected behavior is that it would pan based on different voltages over different channels?
I think I designed it to be a single modulation signal, but I doubt anyone else is using like that, so changing it should be no issue.
I will change it, then you can pull from the source and compile?
I will not push another version for at least a week.
If you can't build, I can probably compile it here on Ubuntu for Windows and send it over.
It would be actually an interesting test to see if it would work.

**Comment by MockbaTheBorg** [comment]
BTW ... in the meantime ... if you want to do poly pan to create stereo spread, just take a look at the new modules I just released. There's one called Automatic Stereo Spreader (ASSprdr, no pun intented).
Maybe that could be useful.

**Comment by MockbaTheBorg** [comment]
There you go, PolyPan:
![image](https://user-images.githubusercontent.com/16762507/74356352-33eaaf80-4d8c-11ea-917b-a5fb20381b21.png)

**Comment by MockbaTheBorg** [comment]
Here's the link for a Linux build I made here on "Ubuntu for Windows", if this works for you then I would ask you a favor: do a checkup on the free modules, suggest what you think would be good to have, then I can make builds for you with the changes without having to wait for the library update cycle.

Thanks!!!

https://mega.nz/#!kfpXURhL!OT3xAdwxbqvlNXKomSQ5gFZWpAtyn0Et5ypTkHud_TA

**Comment by glocke01** [comment]
Do you mean suggestions for new modules or for changes to the existing ones?

Some module ideas I have that I believe would be relatively easy to implement are: simple comb filter that takes v/O and contains no nonlinearities, and a VCV implementation of Ringz with a similar parameter scheme http://doc.sccode.org/Classes/Ringz.html (SC is GPL3 http://doc.sccode.org/Other/Licensing.html). AFAIK, there are no modules that perform either task in the plugin manager. (Ringz is a bpf with insanely high Q but it doesn't self-oscillate, making it useful for pinging/whistling wind sounds, modal synthesis, or as a wobbly sine oscillator with built in envelope follower, etc.)

**Comment by MockbaTheBorg** [comment]
I was talking about the current modules, but I will definitely check those
two.

**Comment by glocke01** [comment]
Suggestions:

- feidah/feidahS
  - default knob to full on
  - add switch for exponential response
- Phase distortion oscillators
  - Consider adding a DC blocker to the signal path (or maybe add a DC blocker module)
- countah/dividah
  - more documentation on the differences
- selectah
  - switch/right click option to reduce the number of active channels
  - I'm happy to report that when you switch away from a trigger source at the same time that source is emitting a trigger, the selectah successfully blocks the trigger
- filtah
  - I'd prefer the CV to be added to the cutoff rather than treated as V/Octave
- holdah
  - add internal noise
- PSelectah
  - add documentation
  - I haven't much of a clue as to what this thing is supposed to do, but I put VCO's into the inputs and liked the result. It was noisy, of course, but very nice after with some filtering. 
- dualBUFFER
  - I can't tell what this is supposed to do. it seems to be basically a >0 comparator.

Overall, it seems you've used the "knob transforms into CV attenuator when there's a cord in the jack" scheme used by BogAudio. I do not prefer this b/c it means you need to offset and scale your CV inputs. I understand that this is an issue of personal preference, I suppose, but for the filtah in particular it is irksome. Anyway, since you've chosen this scheme, you might want to add a module that scales an input (I prefer to have controls for min/max rather than A*B+C type parameterization).

I hope this is the kind of feedback you were hoping for.

Thanks for making such awesome stuff!

**Comment by MockbaTheBorg** [comment]
Awesome! Yes, this is exactly what I was looking for.
So:
. Indeed exponential response if coming to Feidah, FeidahS, Mixah and others. I will put a right click menu option as we did to Pannah, this way I do not break other people's patches.
. I have no idea how to write a DC blocker, I need to research on this. If you have seen any code example it would help.
. Yeah, the difference between Countah and Dividah is subtle. Basically one counts forward and one counts backward (so it actually divided the clock). You are not seeing a difference because there was a bug on Countah that I just fixed.
. You are correct about Selectah, it should replicate on the output the number of channels of the selected input.
. Filtah is a special case, I will have to figure that one out.
. Holdah: internal noise it is.
. PSelectah is a "AND->OR Mux" or a "Priority Selector", meaning: whatever comes into the "High" input shows up into the output, whatever comes into the "Low" priority input will show up into the output only if its priority is raised, by the "raise" input. So, "Low" and "Raise" go into an AND gate, and the output of this AND gate goes on one side of an OR gate, the "High" input goes on the other side of the OR gate.
. dualBuffer is indeed a >0 detector. The use case is just to turn any >0v signal into a 10v signal. Just like a regular digital buffer. To be honest I just made it because I was adding almost all of the boolean stuff.

Did you try the linux build on your computer? Did it work?

**Comment by glocke01** [comment]
haven't had a chance to try the build you provided... 

WRT a DC blocker, it's just a highpass filter with a very low cutoff. Not a big deal, just that some of the phase distortion oscillators have a non-zero mean when the shape is toward the end range. https://www.dsprelated.com/freebooks/filters/DC_Blocker.html

`  y = x - xm1 + 0.995 * ym1;
  xm1 = x;
  ym1 = y;
`

**Comment by MockbaTheBorg** [comment]
Yup ... I did some research on it last night. I have implemented most of the stuff already, just need to code in the DC Blocker, then the Filtah will be left ... which might require some extra work.
Give the build a try when you have a chance, if it works then maybe I can start providing Linux builds made on my Windows laptop ... :)

**Comment by MockbaTheBorg** [comment]
I have been thinking of writing a "ReVoltah" module, which takes an arbitrary input voltage range and outputs an arbitrary output voltage range, for example: you have a signal that varies from -3v to +5v, and it converts it to vary from 0v to 1v for example. Keeping the shape.
Wondering how I would go about it.

**Comment by glocke01** [comment]
ReVoltah: https://github.com/NicolasNeubauer/noobhour_modules/tree/master/src
The Normaliser module does something like this. See also ReScale from AS modules.

As far as how to implement, I can't tell if this is the question you're asking, but: You either track the min and max of the input signal or make assumptions about that range (e.g. ranges shown in ReScale). Given min A and max B in the input, desired min X and max Y for the output, multiply by `f=(Y-X)/(B-A)`, then subtract `(f*A+X)`. 

Years ago in max/msp, I made a function like this that kept running track of min and max, and I found that adding a reset trigger input was musically useful.

**Comment by MockbaTheBorg** [comment]
I actually made it the simple way, you define the min/max you expect to see on your input, and then the min/max that it will translate to in the output.
It is actually useful for dealing with a few things, it can reverse phases, it can invert trigger, it can scale and offset.
Not sure why I didn't write something like this from the start.
I have just pushed the source to GitHub.
