### ISSUE TITLE
These modules sound good but have too few controls to be terribly useful. I'd be grateful if you could build them out a bit more.

### ISSUE THREAD

**Issue by vogelscheiss** [MockbaTheBorg/MockbaModular#12]
If you were to take whatever DSP you're using and insert it into modules with at least the level of functionality found in the VCV VCO, VCF, VCA, etc. I would happily use them. The Moog filter in particular sounds nice. But a VCO with only one input, one output, and one CV has very little utility to a modular setup. Using this one skinny module more or less requires pairing it with a dual attenuator, which kills the skinnyness regardless. What if rather than separate VCOs for every waveform you were instead to do a single VCO with separate outs for all the waveforms, scalable CVs, etc.

I'm sure you have your reasons for designing things the way you have. Take this for whatever it's worth, or not. Thanks.

**Comment by MockbaTheBorg** [comment]
Hi @vogelscheiss , indeed the free modules are very simplistic. But this is actually on purpose.
Few things are in play here:
1 - I actually started coding for VCV back in October. That's when I wrote "Feidah" which was the very first module I wrote in my whole life, even though I have extensive experience with coding. And my approach was that they would be all the same size, and all as simple as possible, so they could become building blocks of bigger things. And I also make all the knobs, switches, etc. Which is also something I had no experience with until last October.
2 - Those modules I write more as a sandbox to learn DSP coding than anything else. And I write them to test things I will use on other code. Sometimes I think I write them much more for myself than to anyone else, and if you look at all the patches that have been released recently, not a single one has a MockbaModular module on it. (which actually makes me question the time dedicated to the free modules)
3 - I have a few commercial modules, which I consider somewhat successful, which are basically made from (or influenced by) those building blocks. And this is actually the purpose of those building blocks, allow me to bring these more complex modules to people.
4 - I have recently released a new set of modules which were developed via a collaboration between Omri Cohen and me. These are free modules as well, though closed source, which I consider interesting ones too, and still I do not see them being used on patches, LOL.

I do want to accommodate requests from users of my modules, this is why I made the new set of tools (due to requests from Omri), and some fixes/improvements to the MockbaModular set. But to be honest, I got and delivered much more requests for improvements on the commercial modules than on the free ones, which was actually a surprise to me. I was expecting the free modules to be much more demanding than the commercial ones, however the commercial ones are hitting me more, which probably makes sense, as people tend to care more for stuff they paid for I guess.

Cheers,
Marcelo.
